-- ╔═══════════════════════════════════════════════════════════════════════════╗
-- ║  BIZRA GENESIS NODE - SAT-LAB v0.1 SCHEMA                               ║
-- ║  SAT serves BIZRA LAB first: Internal enterprise marketing team        ║
-- ╚═══════════════════════════════════════════════════════════════════════════╝

-- SAT Outbox Queue: Content ready for human approval
CREATE TABLE sat_outbox_items (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    agent_type VARCHAR(50) NOT NULL,          -- 'marketing_director' | 'social_media' | 'content' | 'pr'
    channel_type VARCHAR(50) NOT NULL,        -- 'twitter' | 'linkedin' | 'github' | 'youtube'
    content_title VARCHAR(200),
    content_body TEXT NOT NULL,
    schedule_date TIMESTAMPTZ,
    status VARCHAR(20) NOT NULL DEFAULT 'draft', -- 'draft' | 'approved' | 'published' | 'rejected'
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    published_at TIMESTAMPTZ,
    engagement_metrics JSONB
);

-- Index for querying: all draft items ordered by creation time
CREATE INDEX idx_sat_outbox_status_created_at
    ON sat_outbox_items (status, created_at DESC);

-- SAT Activity Log: What SAT actually did
CREATE TABLE sat_activities (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    agent_type VARCHAR(50) NOT NULL,
    action_type VARCHAR(100) NOT NULL,
    action_details JSONB,
    impact_score INTEGER,  -- 1-10 scale of expected impact
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Index for recent activities
CREATE INDEX idx_sat_activities_created_at
    ON sat_activities (created_at DESC);

-- SAT Recommendations Queue: Growth suggestions from SAT
CREATE TABLE sat_recommendations (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    priority VARCHAR(10) NOT NULL DEFAULT 'medium', -- 'high' | 'medium' | 'low'
    category VARCHAR(50),                           -- 'marketing' | 'partnerships' | 'content'
    recommendation TEXT NOT NULL,
    rationale TEXT,
    actionable_by DATE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Index for recommendations by priority and deadline
CREATE INDEX idx_sat_recommendations_priority_actionable_by
    ON sat_recommendations (priority, actionable_by);

-- Add comments for documentation
-- Content generated by SAT for BIZRA LAB approval and publishing
-- Log of SAT actions and their impact for BIZRA LAB
-- SAT suggestions for BIZRA LAB growth and strategy
