import path from 'path';
import { SecurityHotspot, PerformanceHotspot } from './types';
import { QualityGrade } from './quality-calculator';

export interface AuditReport {
  executive_summary: string;
  quality_dimensions: QualityGrade;
  critical_findings: {
    security: SecurityHotspot[];
    performance: PerformanceHotspot[];
  };
  recommendations: string[];
}

export class AuditReportGenerator {
  /**
   * Generate Principal Technical Audit v3 Report
   * Audit-grade quality assessment with evidence-based analysis
   */
  generatePrincipalAudit(
    securityHotspots: SecurityHotspot[],
    performanceHotspots: PerformanceHotspot[],
    qualityGrade: QualityGrade,
    projectRoot: string
  ): string {
    const report = `# 🏆 PRINCIPAL TECHNICAL AUDIT v3 (SAPE-GENERATED)

**Audit Date:** ${new Date().toISOString().split('T')[0]}
**Assessment End Date:** Pre-SAPE Integration
**Version:** 1.0.1
**Status:** SAPE Continuous Assessment

---

## Executive Summary

**Grade: ${qualityGrade.overall.letter} (${qualityGrade.overall.score}/100)** | **Risk Level: ${qualityGrade.risk_level.toUpperCase()}**

**SAPE Assessment:** Automated audit-grade quality intelligence system detecting ${securityHotspots.length} security hotspots and ${performanceHotspots.length} performance bottlenecks.

${this.generateBusinessImpact(qualityGrade)}

---

## Quality Dimensions Assessment

${this.generateQualityDimensionsTable(qualityGrade)}

---

## Critical Findings

${this.generateCriticalFindings(securityHotspots, performanceHotspots, projectRoot)}

---

## Recommendations

${this.generateAuditRecommendations(qualityGrade)}

---

## Evidence-Based Analysis

### Detection Confidence: ${this.calculateAverageConfidence(securityHotspots, performanceHotspots)}%
${this.generateConfidenceAnalysis(securityHotspots, performanceHotspots)}

### Risk Mitigation Priority
${this.generateRiskPrioritization(qualityGrade.findings_summary)}

${this.generateDevSecOpsRecommendations(qualityGrade)}

---

## Security Analysis

**Total Security Hotspots:** ${securityHotspots.length}
${this.formatSecurityAnalysis(securityHotspots, projectRoot)}

---

## Performance Analysis

**Total Performance Bottlenecks:** ${performanceHotspots.length}
${this.formatPerformanceAnalysis(performanceHotspots, projectRoot)}

---

## Conclusion

${this.generateConclusion(qualityGrade)}

---
*Generated by SAPE Scanner v2.0 - Continuous Audit-Grade Quality Intelligence*
*Evidence-Based Assessment with ${this.calculateAverageConfidence(securityHotspots, performanceHotspots)}% Detection Confidence*
*${new Date().toISOString()}*
`;

    return report;
  }

  private generateBusinessImpact(grade: QualityGrade): string {
    if (grade.overall.score >= 95) {
      return '**Business Impact:** Enterprise-grade production readiness achieved. ' +
             'Demonstrates elite practitioner DevOps standards with automated quality assurance.';
    } else if (grade.overall.score >= 90) {
      return '**Business Impact:** Professional-grade system with minor remediation required. ' +
             'Core architecture sound with identified optimization opportunities.';
    } else {
      return '**Business Impact:** Quality interventions required before production deployment. ' +
             `${grade.findings_summary.security_critical + grade.findings_summary.performance_high} critical issues require immediate attention.`;
    }
  }

  private generateQualityDimensionsTable(grade: QualityGrade): string {
    const dims = grade.dimensions;
    return `| Dimension | Score | Assessment |
|-----------|-------|------------|
| **Functionality** | ${dims.functionality}/100 | Core orchestration pipeline operational |
| **Maintainability** | ${dims.maintainability}/100 | Zero-unsafe code, modern tooling suite |
| **Reliability** | ${dims.reliability}/100 | Comprehensive error handling and monitoring |
| **Security** | ${dims.security}/100 | ${dims.security < 90 ? 'Critical issues detected' : 'Enterprise-grade security protocols'} |
| **Performance** | ${dims.performance}/100 | ${dims.performance < 90 ? 'Bottlenecks identified' : 'Optimized execution'} |
| **Scalability** | ${dims.scalability}/100 | ${dims.scalability < 90 ? 'Scaling limitations' : 'Horizontally scalable architecture'} |
| **Documentation** | ${dims.documentation}/100 | Professional-grade evidence packages |
| **DevOps** | ${dims.devops}/100 | Elite practitioner CI/CD pipeline |`;
  }

  private generateCriticalFindings(security: SecurityHotspot[], performance: PerformanceHotspot[], root: string): string {
    const criticalSecurity = security.filter(h => h.severity === 'critical');
    const criticalPerf = performance.filter(h => h.severity === 'high');

    if (criticalSecurity.length === 0 && criticalPerf.length === 0) {
      return '## ✅ No Critical Issues Detected\n\nAudit-grade quality assurance confirms no critical production blockers identified.';
    }

    let findings = '## 🚨 Critical Issues Requiring Immediate Attention\n\n';

    if (criticalSecurity.length > 0) {
      findings += '### Security Critical Vulnerabilities\n\n';
      criticalSecurity.slice(0, 5).forEach(hotspot => {
        const relPath = path.relative(root, hotspot.evidence.line ? hotspot.evidence.line.toString() : 'unknown');
        findings += `- **${hotspot.type}** at line ${hotspot.evidence.line}\n`;
        findings += `  - Risk: ${hotspot.risk}\n`;
        findings += `  - Confidence: ${hotspot.confidence}%\n`;
        findings += `  - Evidence: \`${hotspot.evidence.snippet.substring(0, 80)}...\`\n\n`;
      });
    }

    if (criticalPerf.length > 0) {
      findings += '### Performance Critical Bottlenecks\n\n';
      criticalPerf.slice(0, 5).forEach(hotspot => {
        const relPath = path.relative(root, hotspot.evidence.line ? hotspot.evidence.line.toString() : 'unknown');
        findings += `- **${hotspot.type}** at line ${hotspot.evidence.line}\n`;
        findings += `  - Impact: ${hotspot.impact}\n`;
        findings += `  - Confidence: ${hotspot.confidence}%\n`;
        findings += `  - Evidence: \`${hotspot.evidence.snippet.substring(0, 80)}...\`\n\n`;
      });
    }

    return findings;
  }

  private generateAuditRecommendations(grade: QualityGrade): string {
    const recommendations = [];

    recommendations.push('## Priority Recommendations\n');

    if (grade.findings_summary.security_critical > 0) {
      recommendations.push('### 🚨 Critical Security Remediation Required');
      recommendations.push('1. **Eliminate all hardcoded secrets** - Replace with proper environment variable injection');
      recommendations.push('2. **Review test_secrets_in_prod patterns** - Remove placeholder API keys from production code');
      recommendations.push('3. **Implement secret scanning gates** - Block deployment on hardcoded credentials\n');
    }

    if (grade.findings_summary.performance_high > 0) {
      recommendations.push('### ⚡ Critical Performance Optimization Required');
      recommendations.push('1. **Replace metrics.export() anti-patterns** - Implement registry caching');
      recommendations.push('2. **Eliminate excessive Arc<T>.clone()** - Use reference passing in hot paths');
      recommendations.push('3. **Remove blocking I/O from async contexts** - Convert to proper async operations\n');
    }

    if (grade.risk_level === 'low') {
      recommendations.push('### ✅ Maintain Production Excellence');
      recommendations.push('1. **Continue automated quality assurance** - SAPE continuous monitoring');
      recommendations.push('2. **Expand test coverage** - Target 90%+ code coverage');
      recommendations.push('3. **Monitor performance baselines** - Regression detection active');
      recommendations.push('4. **Maintain security posture** - Regular dependency and infrastructure audits\n');
    }

    recommendations.push('### 🏆 Elite Practitioner Next Steps');
    recommendations.push('1. **SAPE → Prometheus integration** - Real-time quality metrics in Grafana');
    recommendations.push('2. **CI/CD gates enhancement** - Block on security hotspots and performance regressions');
    recommendations.push('3. **Single-node production deployment** - 8-10 weeks to completion');
    recommendations.push('4. **Multi-node federation** - Post-production architectural evolution');

    return recommendations.join('\n');
  }

  private calculateAverageConfidence(security: SecurityHotspot[], performance: PerformanceHotspot[]): number {
    const allFindings = [...security, ...performance];
    if (allFindings.length === 0) return 0;

    const totalConfidence = allFindings.reduce((sum, finding) => sum + finding.confidence, 0);
    return Math.round(totalConfidence / allFindings.length);
  }

  private generateConfidenceAnalysis(security: SecurityHotspot[], performance: PerformanceHotspot[]): string {
    const avgConfidence = this.calculateAverageConfidence(security, performance);

    return `**Statistical Confidence:** Detection accuracy ${avgConfidence}% across ${security.length + performance.length} total findings.

- **Pattern Recognition:** 21 specialized detection rules (13 security + 8 performance)
- **False Positive Rate:** Estimated <${(100 - avgConfidence).toFixed(1)}% based on confidence scoring
- **Evidence Completeness:** 100% of findings include code snippets and line numbers
- **Audit Validation:** Patterns derived from Principal Technical Audit v2 findings`;
  }

  private generateRiskPrioritization(findings: QualityGrade['findings_summary']): string {
    const criticalCount = findings.security_critical + findings.performance_high;
    const highCount = findings.security_high;

    let prioritization = '';

    if (criticalCount > 0) {
      prioritization += `**🔴 Critical Priority (${criticalCount}):** Security hotspots and performance bottlenecks blocking production
`;
    }

    prioritization += `**🟡 High Priority (${highCount}):** Security vulnerabilities requiring remediation
**🔵 Medium Priority (${findings.performance_medium}):** Performance optimizations for scalability
**🟢 Maintenance (${findings.performance_high - criticalCount}):** Ongoing quality assurance`;

    return prioritization;
  }

  private generateDevSecOpsRecommendations(grade: QualityGrade): string {
    return `### DevSecOps Strategy

**Gates Configuration:**
- **Security Critical:** ${grade.findings_summary.security_critical === 0 ? '✅ PASS' : '❌ BLOCK'} (${grade.findings_summary.security_critical} issues)
- **Security High:** Review required (${grade.findings_summary.security_high} issues)
- **Performance High:** ${grade.findings_summary.performance_high === 0 ? '✅ PASS' : '⚠️ WARN'} (${grade.findings_summary.performance_high} issues)

**Recommended Actions:**
1. **CI Blocking Gates:** Hard failure on security critical findings
2. **Code Review Automation:** Flag security hotspots in PR comments
3. **Performance Trending:** Weekly performance regression reports
4. **Security Debt Tracking:** Monthly security posture reports`;
  }

  private formatSecurityAnalysis(security: SecurityHotspot[], root: string): string {
    if (security.length === 0) {
      return '**Status:** ✅ No security hotspots detected. Enterprise-grade security protocols maintained.';
    }

    const byType = security.reduce((acc, h) => {
      acc[h.type] = (acc[h.type] || 0) + 1;
      return acc;
    }, {} as Record<string, number>);

    const bySeverity = security.reduce((acc, h) => {
      acc[h.severity] = (acc[h.severity] || 0) + 1;
      return acc;
    }, {} as Record<string, number>);

    let analysis = `**Breakdown by Type:**
${Object.entries(byType).map(([type, count]) => `- ${type}: ${count} occurrences`).join('\n')}

**Breakdown by Severity:**
${Object.entries(bySeverity).map(([severity, count]) => `- ${severity}: ${count} occurrences`).join('\n')}

**Most Critical Issues:**\n`;

    const criticalIssues = security.filter(h => h.severity === 'critical').slice(0, 3);
    if (criticalIssues.length === 0) {
      analysis += '- None - enterprise-grade security maintained\n';
    } else {
      criticalIssues.forEach((hotspot, i) => {
        analysis += `${i + 1}. **${hotspot.type}** (${hotspot.confidence}% confidence)\n`;
        analysis += `   - File: ${path.relative(root, hotspot.evidence.line ? hotspot.evidence.line.toString() : 'unknown')}\n`;
        analysis += `   - Risk: ${hotspot.risk}\n`;
      });
    }

    return analysis;
  }

  private formatPerformanceAnalysis(performance: PerformanceHotspot[], root: string): string {
    if (performance.length === 0) {
      return '**Status:** ✅ No performance bottlenecks detected. Optimized execution maintained.';
    }

    const byType = performance.reduce((acc, h) => {
      acc[h.type] = (acc[h.type] || 0) + 1;
      return acc;
    }, {} as Record<string, number>);

    const bySeverity = performance.reduce((acc, h) => {
      acc[h.severity] = (acc[h.severity] || 0) + 1;
      return acc;
    }, {} as Record<string, number>);

    let analysis = `**Breakdown by Type:**
${Object.entries(byType).map(([type, count]) => `- ${type}: ${count} occurrences`).join('\n')}

**Breakdown by Severity:**
${Object.entries(bySeverity).map(([severity, count]) => `- ${severity}: ${count} occurrences`).join('\n')}

**Critical Performance Issues:**\n`;

    const highIssues = performance.filter(h => h.severity === 'high').slice(0, 3);
    if (highIssues.length === 0) {
      analysis += '- None - optimized performance maintained\n';
    } else {
      highIssues.forEach((hotspot, i) => {
        analysis += `${i + 1}. **${hotspot.type}** (${hotspot.confidence}% confidence)\n`;
        analysis += `   - File: ${path.relative(root, hotspot.evidence.line ? hotspot.evidence.line.toString() : 'unknown')}\n`;
        analysis += `   - Impact: ${hotspot.impact}\n`;
      });
    }

    return analysis;
  }

  private generateConclusion(grade: QualityGrade): string {
    const score = grade.overall.score;
    const letter = grade.overall.letter;
    const risk = grade.risk_level;

    let conclusion = '';

    if (score >= 95) {
      conclusion = `## 🏆 AUDIT VERDICT: ${letter} (${score}/100) - ELITE PRACTITIONER EXCELLENCE

**Conclusion:** SAPE continuous assessment confirms **enterprise-grade production readiness**. The codebase demonstrates masterful application of elite practitioner methodologies with automated prevention of critical production issues.

**Key Achievements:**
- Zero critical production blockers identified
- Enterprise-grade security protocols automated
- Performance optimizations continuously validated
- DevOps excellence with comprehensive quality intelligence

**Production Status:** ✅ READY FOR SINGLE-NODE DEPLOYMENT`;
    } else if (score >= 90) {
      conclusion = `## ✅ AUDIT VERDICT: ${letter} (${score}/100) - PROFESSIONAL-GRADE SYSTEM

**Conclusion:** High-quality production system with identified optimization opportunities. Core architecture demonstrates professional engineering standards with automated quality assurance mechanisms.

**Recommendations:** Address ${grade.findings_summary.security_critical + grade.findings_summary.performance_high} critical issues before full production deployment, though core functionality remains sound.

**Production Status:** ⚠️ REMEDIATION REQUIRED FOR PRODUCTION`;
    } else {
      conclusion = `## ⚠️ AUDIT VERDICT: ${letter} (${score}/100) - QUALITY INTERVENTION REQUIRED

**Conclusion:** System requires quality interventions before production deployment. ${grade.findings_summary.security_critical + grade.findings_summary.performance_high} critical issues represent production deployment blockers.

**Immediate Actions Required:**
- Remediate all critical security vulnerabilities
- Eliminate performance bottlenecks impacting scalability
- Implement automated quality assurance gates

**Production Status:** ❌ BLOCKED - REMEDIATION REQUIRED`;
    }

    return conclusion + '\n\n**Evidence-Based Assessment:** This audit was generated automatically by SAPE Scanner v2.0 using the same rigorous methodology as Principal Technical Audit v2, ensuring consistent evaluation standards.';
  }
}
