// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface AgentResponse { agent_id: string, content: string, metadata: any, message_id: string, is_streaming: boolean, is_complete: boolean, }