// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface AuthResponse { success: boolean, user_id: string | null, error: string | null, session_id: string | null, }