// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MessageType = "authenticate" | "auth_response" | "agent_message" | "agent_response" | "typing_indicator" | "presence_update" | "system_message" | "error" | "ping" | "pong";