// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MessageType } from "./MessageType";

export interface WebSocketMessage { message_type: MessageType, payload: any, timestamp: bigint, message_id: string, session_id: string | null, }